version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout:
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install -y g++-7'
      - run:
          name: Install build-essentials
          command: 'sudo apt-get install -y build-essential'
      - run:
          name: Install git
          command: 'sudo apt install -y git-all'
      - run:
          name: Install wget
          command: 'sudo apt-get install -y wget'
      - run:
          name: Install CMake
          command: |
            wget https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
            tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz
            echo "export PATH=$PWD/cmake-3.14.0-Linux-x86_64/bin:$PATH" >> $BASH_ENV
      - run:
          name: Build
          command: 'mkdir build && cd build && cmake .. && make'
      - run:
          name: Run Tests
          command: 'cd test/unittest && ctest'
