version: 2
jobs:
  build:
    docker:
      - image: "gcc:8.2"
    steps:
      - checkout:
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install build-essentials
          command: 'sudo apt-get update && sudo apt-get install -y build-essential'
      - run:
          name: Install git
          command: 'sudo apt install -y git-all'
      - run:
          name: Install wget
          command: 'sudo apt-get install -y wget'
      - run:
          name: Install CMake
          command: |
            wget https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
            tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz
            echo "export PATH=$PWD/cmake-3.14.0-Linux-x86_64/bin:$PATH" >> $BASH_ENV
      - run:
          name: Install JDK
          command: 'sudo apt-get install -y default-jdk'
      - run:
          name: Build and test
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug
            make
            cd test/unittest && ctest
