name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run:  mkdir build && cd build && cmake -DTESTS=On ..
    - name: make
      run: make
    - name: tests
      run: cd test/unittests && ctest
